### ISSUE TITLE
Missing Dataset

### ISSUE THREAD

**Issue by jocacace** [przemekMal/Circular-YOLO-circle-detection#1]
Is the dataset available somewhere to train the model? Otherwise, are the weights somewhere to use them without the training?

**Comment by przemekMal** [comment]
Hi Jonathan,

Thank you for your interest!

You can use any dataset to train the model, including publicly available ones. Here are three examples of general-purpose datasets that might work for your training needs:

    https://data.acfr.usyd.edu.au/ag/treecrops/2016-multifruit
    https://www.researchgate.net/publication/338495204_MinneApple_A_Benchmark_Dataset_for_Apple_Detection_and_Segmentation
    https://rex.libraries.wsu.edu/esploro/outputs/dataset/99900502619401842 [ArtificialLight]

Additionally, if you'd like, I can share the datasets I specifically used for training:

    https://drive.google.com/file/d/1K3eiYbiCIA80Iiv2BgBTG69pnR6jwMNq/view?usp=drive_link
    https://drive.google.com/file/d/13iS0qAVI8nMP7TIO3DuQK0J_yYtlU8yY/view?usp=drive_link
    https://drive.google.com/file/d/1uC3pzIzccvsTASOxKBP213St1Xifjh5Y/view?usp=drive_link

If you'd prefer to skip the training process, you can also use the pre-trained weights I’ve provided:

    YOLOv1-02:  https://drive.google.com/file/d/1DhqfTA2Pqcy4zOx-R2WzPtBNubcJ0JlY/view?usp=sharing
    YOLOv3: https://drive.google.com/file/d/1_-m2Kdpsc60cmd4V9OElAyRif4OFVZMu/view?usp=sharing

Feel free to reach out if you have any other questions or need assistance!

Best regards,
przemekMal
